# Generated by Django 5.2.1 on 2026-06-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_installments',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
