# Generated by Django 5.2.1 on 2026-06-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='payment_invoices/'),
        ),
    ]
