# Generated by Django 5.2.1 on 2026-05-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_course_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mode_of_study',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PHYSICAL', 'Physical')], default='PHYSICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='number_of_installments',
            field=models.PositiveIntegerField(choices=[(1, '1 Installment'), (2, '2 Installments'), (3, '3 Installments'), (4, '4 Installments'), (6, '6 Installments'), (12, '12 Installments')], default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='original_course_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='preferred_payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
