# Generated by Django 5.2.1 on 2026-05-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('SEM1', 'Semester 1'), ('SEM2', 'Semester 2'), ('SEM3', 'Semester 3'), ('SEM4', 'Semester 4')], default='SEM1', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
