# Generated by Django 5.2.1 on 2026-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_semester_course_total_hours'),
        ('lecturers', '0002_alter_lecturer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ManyToManyField(blank=True, related_name='courses', to='lecturers.lecturer'),
        ),
    ]
